services:
  app:
    entrypoint: ["/bin/sh", "/app/scripts/server-entrypoint.sh"]
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      FETCH: ${FETCH:-true}
      TEST: ${TEST:-false}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-movies}?schema=public
    working_dir: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.movies.rule=Host(`movies.rpi.lan`) || Host(`movies.rpi.local`) || Host(`rpi.local`)"
      - "traefik.http.routers.movies.entrypoints=https"
      - "traefik.http.routers.movies.tls=true"
      - "coolify.managed=true"

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-movies}
    # ports:
    #   - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
